### ISSUE TITLE
[Flaky Test] undefined method `casecmp' for nil:NilClass  

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14693]
## Background/context/resources

```
JudgeSchedulePeriod  judges are not assigned hearings on their travel board days, the week before, or the week after verifies judge algo cannot assign judge to week prior or after assigned TB week
 
     Failure/Error: vacols_judges[vlj_id][:first_name].casecmp(name.split(", ")[1].strip.downcase).zero? &&
 

 
     NoMethodError:
 
       undefined method `casecmp' for nil:NilClass
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:53:in `judge_in_vacols?'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:77:in `block in filter_judges_not_in_db'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:77:in `select'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:77:in `filter_judges_not_in_db'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:93:in `validate_judge_non_availability_dates'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:101:in `validate'
 
     # ./app/models/judge_schedule_period.rb:13:in `validate_spreadsheet'
 
     # ./spec/models/judge_schedule_period_spec.rb:7:in `block (2 levels) in <top (required)>'
 
     # ./spec/models/judge_schedule_period_spec.rb:89:in `block (3 levels) in <top (required)>'
 

 
  3) JudgeSchedulePeriod  judges are not assigned hearings on their travel board days, the week before, or the week after verify period is covered by both judges
 
     Failure/Error: vacols_judges[vlj_id][:first_name].casecmp(name.split(", ")[1].strip.downcase).zero? &&
 

 
     NoMethodError:
 
       undefined method `casecmp' for nil:NilClass
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:53:in `judge_in_vacols?'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:77:in `block in filter_judges_not_in_db'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:77:in `select'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:77:in `filter_judges_not_in_db'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:93:in `validate_judge_non_availability_dates'
 
     # ./app/services/hearing_schedule/validate_judge_spreadsheet.rb:101:in `validate'
 
     # ./app/models/judge_schedule_period.rb:13:in `validate_spreadsheet'
 
     # ./spec/models/judge_schedule_period_spec.rb:7:in `block (2 levels) in <top (required)>'
 
     # ./spec/models/judge_schedule_period_spec.rb:89:in `block (3 levels) in <top (required)>'
 
```

 - Circle CI Error:  [undefined method `casecmp' for nil:NilClass](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/33139/workflows/fde1e922-b844-432d-9328-f60b8cad71ce/jobs/121819/parallel-runs/4?filterBy=FAILED)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue
